version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-products
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: products-db
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo_data:/data/db
  
# Connection string to put on compass: mongodb://admin:admin123@localhost:27017


  products-api:
    build:
      context: .
      dockerfile: Products/Products.Api/Dockerfile
    container_name: products-api
    restart: always
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://admin:admin123@mongodb:27017
      - MongoDbSettings__DatabaseName=products-db
    depends_on:
      - mongodb

volumes:
  mongo_data:
